aliases:
    amerge: pr merge --auto
    prco: pr checkout
    prls: pr list
    prcr: pr create
    prv: pr view --web
    rc: repo clone
    rcr: repo create --source . --push
    rv: repo view --web
    pr-files: pr view --json files --jq '.files.[].path'
    reviews: pr list --search "user-review-requested:@me"
    prs: pr list
git_protocol: ssh
version: "1"
